---
title: "Data2401Final"
author: "Kevin Sheard, John Beall, Andrew Vo"
date: "`r Sys.Date()`"
output: slidy_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = F,
	message = FALSE,
	warning = FALSE
)
```

```{r}
# Load tidyverse for manipulating data
#Load ggplot2, and plotly for graphing data
library(tidyverse, warn.conflicts = F)
library(ggplot2, warn.conflicts = F)
library(plotly, warn.conflicts = F)
library(shiny, warn.conflicts = F)
library(ggthemes, warn.conflicts = F)
```

```{r}
#Read in the energy data
energy = read_csv("archive/organised_Gen.csv")

```

```{r}
#renaming the columns and removing the "ID" column
colnames(energy) = c("ID", "year", "month", "state", "producer", "source", "generation")
energy = energy %>% select(-`ID`)
```

## Glimpse of the Energy Dataset

```{r}
energy$Date<-as.Date(with(energy,paste(year,month,Day = 1,sep="-")),"%Y-%m-%d")
glimpse(energy)
```

## US Power Generation

```{r}
energy %>% 
  filter(producer == "Total Electric Power Industry", state == "US-TOTAL") %>% 
  ggplot() + 
  geom_point(aes(x = year, y = generation/1000000, color = source)) +
  geom_smooth(aes(x = year, y = generation/1000000, color = source)) +
  labs(title = "US total power generation per year", y = "Generation(TWH)", x = "Year")
  

energy %>% 
  filter(producer == "Total Electric Power Industry", state == 'US-TOTAL', source == 'Total') %>% 
  ggplot(aes(group = month, x = month, y = generation, fill = month))+
  geom_boxplot() +
  scale_x_continuous(breaks = c(1:12))
```

## US Power Generation

```{r fig.height=8, fig.width=5}
total_energy = energy %>% filter(producer == "Total Electric Power Industry", state != "US-TOTAL") 
fig = energy %>% 
  filter(producer == "Total Electric Power Industry", state != "US-TOTAL") %>% 
  group_by(year, month, state) %>% 
  summarize(total = sum(generation)/2) %>% 
  right_join(total_energy) %>%
  filter(source != "Total") %>% 
  arrange(total) %>% 
  ggplot() +
  geom_col(aes(x = state, y = generation/1000000, fill = source)) +
  labs(title = "US Power Generation by State", y = "Generation(TWH)", x = "State") +
  coord_flip()

fig
```

## Texas Power Generation

```{r}
energy %>% 
  filter(producer == "Total Electric Power Industry", state == "TX") %>% 
  ggplot() + 
  geom_point(aes(x = year, y = generation/1000000, color = source)) +
  geom_smooth(aes(x = year, y = generation/1000000, color = source)) +
  labs(title = "Texas monthly average power generation per year", x = "Year", y = "Power Generation(TWH)")


energy %>% 
  filter(producer == "Total Electric Power Industry", state == "TX") %>% 
  ggplot() + 
  geom_point(aes(x = month, y = generation/1000000, color = source)) +
  geom_smooth(aes(x = month, y = generation/1000000, color = source)) +
  labs(title = "Texas total power generation per month", x = "Month", y = "Power Generation(TWH)")
```

## Texas Power Generation

```{r fig.height=20}

ui <- fluidPage(
  # App title ----
  titlePanel("Texas Total Power Generation Over Time"),
  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      position = "right",
      
      checkboxGroupInput("sources", 
        label = h3("Source:"), 
        choices = unique(energy$source),
        selected = "Total"),
      
      checkboxInput("facetStatus",
                    "Facet",
                    value = TRUE)
    ),

    # Main panel for displaying outputs ----
    mainPanel(
      # Output: HTML table with requested number of observations ----
      plotlyOutput("totalGenPlot",
                   width = "100%",
                   height = "100%")
    )
  )
)

server = function(input, output){
  shinyEnergy = reactive({
    energy %>% filter(producer == "Total Electric Power Industry", state == "TX", year != 2022, source == input$sources) %>% group_by(Date, source) %>% 
    summarize(total_generation = sum(generation)) %>% mutate(total_generation = total_generation / 1000000)
  })

  output$totalGenPlot = renderPlotly({
    fig2 = shinyEnergy() %>% 
    ggplot() +
    geom_line(aes(x= Date, y= total_generation, color = source)) +
    geom_smooth(aes(x = Date, y= total_generation, color = source)) +
    labs(title = "Texas Total Power Generation Over Time", x = "Date", y = "Power Generation(TWH)")
    
    facetEnergy = reactive({
      if(input$facetStatus == T){
        fig2 + facet_wrap(~source)
      }
      else{
        fig2
      }
    })
    
    fig2 = facetEnergy()
    ggplotly(fig2, tooltip = c("x", "y", "source"))
  })
}

shinyApp(ui = ui, server = server)
```

## Others

```{r}
energy %>% 
  filter(producer == "Total Electric Power Industry", state != "US-TOTAL", generation < -5000) %>% 
  ggplot() +
  geom_point(aes(x = state, y = generation, color = source)) +
  labs(title = "States with negative power generation (<-5000)")
```

## US Power Generation

```{r}

ui <- fluidPage(
  # App title ----
  titlePanel("Total Power Generation Over Time"),
  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      position = "right",
      
      checkboxGroupInput("sources", 
        label = h3("Source:"), 
        choices = unique(energy$source),
        selected = "Total"),
      
      checkboxInput("facetStatus",
                    "Facet",
                    value = TRUE),
  
      hr(),
      fluidRow(column(3, verbatimTextOutput("value")))
    ),

    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Verbatim text for data summary ----
      verbatimTextOutput("summary"),
      # Output: HTML table with requested number of observations ----
      plotlyOutput("totalGenPlot")
    )
  )
)

server = function(input, output){
  shinyEnergy = reactive({
    energy %>% filter(producer == "Total Electric Power Industry", state != "US-TOTAL", year != 2022, source == input$sources) %>% group_by(Date, source) %>% 
    summarize(total_generation = sum(generation)) %>% mutate(total_generation = total_generation / 1000000)
  })
  
  
  
  output$totalGenPlot = renderPlotly({
    fig2 = shinyEnergy() %>% 
    ggplot() +
    geom_line(aes(x= Date, y= total_generation, color = source)) +
    geom_smooth(aes(x = Date, y= total_generation, color = source)) +
    labs(title = "Total Power Generation Over Time", x = "Date", y = "Power Generation(TWH)")
    
    facetEnergy = reactive({
      if(input$facetStatus == T){
        fig2 + facet_wrap(~source)
      }
      else{
        fig2
      }
    })
    
    fig2 = facetEnergy()
    ggplotly(fig2, tooltip = c("x", "y", "source"))
  })
}

shinyApp(ui = ui, server = server)
```

## Andrew

Contributions below will include: Texas Power Dist, US Power Generation Per Year, Total US power distribution over months, TX power distribution over months

```{r}
energy %>% count(producer)

energy %>% count(source)

#Texas Power Dist
energy %>% 
  filter(producer != "Total Electric Power Industry", state == 'TX', source != 'Total') %>%
  ggplot() + 
  geom_col(aes(x = producer, y = generation, fill = source)) +
  labs(title = "TX Power Distribution") +
  theme(axis.text.x = element_text(angle = -25, vjust = .5, hjust = .1))

#US Power Generation Per Year
energy %>% 
  filter(producer != "Total Electric Power Industry", state == "US-TOTAL", source != 'Total', year <= 2021) %>% 
  ggplot() + 
  geom_col(aes(x = year, y = generation, fill = source)) +
  labs(title = "US Power Generation Per Year")

#Total US power distribution over months
energy %>% 
  filter(producer == "Total Electric Power Industry", state == 'US-TOTAL', source == 'Total') %>% 
  ggplot(aes(group = month, x = month, y = generation, fill = month))+
  geom_boxplot() +
  scale_x_continuous(breaks = c(1:12))


#TX power distribution over months
energy %>% 
  filter(producer == "Total Electric Power Industry", state == 'TX', source == 'Total') %>% 
  ggplot(aes(group = month, x = month, y = generation, fill = month))+
  geom_boxplot() +
  scale_x_continuous(breaks = c(1:12))+
  labs(title = 'TX Power Distribution Over Months')

energy %>% 
  filter(producer != "Total Electric Power Industry", state == 'TX', source != 'Total') %>% 
  ggplot()+
  geom_col(aes(x = month, y = generation, fill = source)) +
  labs(title = 'Texas Monthly Power Distribution Per Month')+
  scale_x_continuous(breaks = c(1:12))
```

## Energy Sources amoung producer types

```{r}
#US Energy Sources Among Producer Types in 2020
energy %>% 
  group_by(source, producer) %>% 
  filter(source != 'Total', year == 2020) %>% 
  ggplot() + 
  geom_col(aes(x = producer, y = generation, fill = source)) +
  labs(title = "US Energy Sources Among Producer Types in 2020")+
  theme(axis.text.x = element_text(angle = -15, vjust = 1, hjust = .1))

#TX Energy Sources Among Producer Types in 2020
energy %>% 
  group_by(source, producer, state) %>% 
  filter(source != 'Total', year == 2020, state == "TX") %>% 
  ggplot() + 
  geom_col(aes(x = producer, y = generation, fill = source)) +
  labs(title = "TX Energy Sources Among Producer Types in 2020")+
  theme(axis.text.x = element_text(angle = -15, vjust = 1, hjust = .1))
```
